/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Vue 3 Project Template API
 * OpenAPI spec version: 1.0.0
 */

export type PostLogin200 = {
  /** JWT token */
  token?: string;
  /** Success flag */
  success?: boolean;
  /** Success message */
  message?: string;
  /** HTTP status code */
  status_code?: number;
};
