/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Vue 3 Project Template API
 * OpenAPI spec version: 1.0.0
 */

export type PostLogin401 = {
  /** Error message */
  message?: string;
  /** Error code */
  error_code?: string;
  /** HTTP status code */
  status_code?: number;
  /** Success flag */
  success?: boolean;
};
