/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Vue 3 Project Template API
 * OpenAPI spec version: 1.0.0
 */

export type PostLoginBody = {
  /** email */
  email: string;
  /** Password */
  password: string;
};
