/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Vue 3 Project Template API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/vue-query';
import type { MutationFunction, QueryClient, UseMutationOptions, UseMutationReturnType } from '@tanstack/vue-query';

import { unref } from 'vue';
import type { MaybeRef } from 'vue';

import type { PostLogin200, PostLogin401, PostLoginBody } from '../../models';

import { customInstance } from '../../../../lib/axios/lib';
import type { ErrorType, BodyType } from '../../../../lib/axios/lib';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Login
 */
export const postLogin = (
  postLoginBody: MaybeRef<PostLoginBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  postLoginBody = unref(postLoginBody);

  return customInstance<PostLogin200>(
    { url: `/login`, method: 'POST', headers: { 'Content-Type': 'application/json' }, data: postLoginBody, signal },
    options,
  );
};

export const getPostLoginMutationOptions = <TError = ErrorType<PostLogin401>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postLogin>>,
    TError,
    { data: BodyType<PostLoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError, { data: BodyType<PostLoginBody> }, TContext> => {
  const mutationKey = ['postLogin'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLogin>>, { data: BodyType<PostLoginBody> }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return postLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postLogin>>>;
export type PostLoginMutationBody = BodyType<PostLoginBody>;
export type PostLoginMutationError = ErrorType<PostLogin401>;

/**
 * @summary Login
 */
export const usePostLogin = <TError = ErrorType<PostLogin401>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postLogin>>,
      TError,
      { data: BodyType<PostLoginBody> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postLogin>>,
  TError,
  { data: BodyType<PostLoginBody> },
  TContext
> => {
  const mutationOptions = getPostLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
